server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crazy-task-tracker
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 151460qw
  jpa:
    hibernate:
      ddl-auto: create-drop
